OpenSource - Updated post about first Debian GNU/Linux configuration - added bash alias about variables check

diff --git a/static/static/openSource/DebianFirstConfig/user/bash_functions b/static/static/openSource/DebianFirstConfig/user/bash_functions
--- a/static/static/openSource/DebianFirstConfig/user/bash_functions
+++ b/static/static/openSource/DebianFirstConfig/user/bash_functions
@@ -1008,6 +1008,47 @@ tagAllMp3File()  {
 # Check files to burn  #
 ########################
 
+# Check all variables are defined
+## Run: checkAllVarsDefined JAVA_HOME PROVA_MIA
+checkAllVarsDefined() {
+    # Controlla se sono stati passati parametri
+    if [ $# -eq 0 ]; then
+        return 1  # Errore: nessun parametro fornito
+    fi
+
+    for var in "$@"; do
+        if [[ ! -v $var ]]; then
+            echo "Errore: variabile '$var' non definita." >&2
+            return 2  # Errore: variabile non definita
+        fi
+    done
+}
+export -f checkAllVarsDefined
+
+# Check all variables are not empty
+## Run: checkAllVarsNotEmpty JAVA_HOME ID MY_TEST
+checkAllVarsNotEmpty() {
+    # Controlla se sono stati passati parametri
+    if [ $# -eq 0 ]; then
+        return 1  # Errore: nessun parametro fornito
+    fi
+
+    for var in "$@"; do
+        # Controlla se la variabile è non definita o vuota
+        if [[ ! -v $var || -z "${!var}" ]]; then
+            echo "Errore: variabile '$var' non definita o vuota." >&2
+            return 2  # Errore: variabile non definita o vuota
+        fi
+    done
+
+    return 0  # Tutte le variabili sono definite e non vuote
+}
+export -f checkAllVarsNotEmpty
+
+########################
+# Check files to burn  #
+########################
+
 checkFilesToBurn() {
 
   # Ultimo aggiornamento 2022-06-20
